-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [agent_bridle_ceremony]: function definitions
import Aeneas
import AgentBridleCeremony.Types
import AgentBridleCeremony.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace agent_bridle_ceremony

/-- [agent_bridle_ceremony::authority::{impl core::clone::Clone for agent_bridle_ceremony::authority::Effect}::clone]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:9-18:14
    Visibility: public -/
def authority.Effect.Insts.CoreCloneClone.clone
  (self : authority.Effect) : Result authority.Effect := do
  ok self

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::clone::Clone for agent_bridle_ceremony::authority::Effect}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:9-18:14 -/
@[reducible]
def authority.Effect.Insts.CoreCloneClone : core.clone.Clone authority.Effect
  := {
  clone := authority.Effect.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::marker::Copy for agent_bridle_ceremony::authority::Effect}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:16-18:20 -/
@[reducible]
def authority.Effect.Insts.CoreMarkerCopy : core.marker.Copy authority.Effect
  := {
  cloneInst := authority.Effect.Insts.CoreCloneClone
}

/-- [agent_bridle_ceremony::authority::{impl core::fmt::Debug for agent_bridle_ceremony::authority::Effect}::fmt]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:22-18:27
    Visibility: public -/
def authority.Effect.Insts.CoreFmtDebug.fmt
  (self : authority.Effect) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | authority.Effect.Deny => core.fmt.Formatter.write_str f (toStr "Deny")
  | authority.Effect.Allow => core.fmt.Formatter.write_str f (toStr "Allow")

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::fmt::Debug for agent_bridle_ceremony::authority::Effect}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:22-18:27 -/
@[reducible]
def authority.Effect.Insts.CoreFmtDebug : core.fmt.Debug authority.Effect := {
  fmt := authority.Effect.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::marker::StructuralPartialEq for agent_bridle_ceremony::authority::Effect}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:29-18:38 -/
@[reducible]
def authority.Effect.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq authority.Effect := {
}

/-- [agent_bridle_ceremony::authority::{impl core::cmp::PartialEq<agent_bridle_ceremony::authority::Effect> for agent_bridle_ceremony::authority::Effect}::eq]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:29-18:38
    Visibility: public -/
def authority.Effect.Insts.CoreCmpPartialEqEffect.eq
  (self : authority.Effect) (other : authority.Effect) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::cmp::PartialEq<agent_bridle_ceremony::authority::Effect> for agent_bridle_ceremony::authority::Effect}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:29-18:38 -/
@[reducible]
def authority.Effect.Insts.CoreCmpPartialEqEffect : core.cmp.PartialEq
  authority.Effect authority.Effect := {
  eq := authority.Effect.Insts.CoreCmpPartialEqEffect.eq
}

/-- [agent_bridle_ceremony::authority::{impl core::cmp::Eq for agent_bridle_ceremony::authority::Effect}::assert_fields_are_eq]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:40-18:42
    Visibility: public -/
def authority.Effect.Insts.CoreCmpEq.assert_fields_are_eq
  (self : authority.Effect) : Result Unit := do
  ok ()

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::cmp::Eq for agent_bridle_ceremony::authority::Effect}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:40-18:42 -/
@[reducible]
def authority.Effect.Insts.CoreCmpEq : core.cmp.Eq authority.Effect := {
  partialEqInst := authority.Effect.Insts.CoreCmpPartialEqEffect
  assert_fields_are_eq := authority.Effect.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [agent_bridle_ceremony::authority::{impl core::hash::Hash for agent_bridle_ceremony::authority::Effect}::hash]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:44-18:48
    Visibility: public -/
def authority.Effect.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : authority.Effect) (state : __H) :
  Result __H
  := do
  let self1 := read_discriminant self
  Isize.Insts.CoreHashHash.hash corehashHasherInst self1 state

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::hash::Hash for agent_bridle_ceremony::authority::Effect}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 18:44-18:48 -/
@[reducible]
def authority.Effect.Insts.CoreHashHash : core.hash.Hash authority.Effect := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    authority.Effect.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [agent_bridle_ceremony::authority::{impl core::clone::Clone for agent_bridle_ceremony::authority::Assurance}::clone]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:9-27:14
    Visibility: public -/
def authority.Assurance.Insts.CoreCloneClone.clone
  (self : authority.Assurance) : Result authority.Assurance := do
  ok self

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::clone::Clone for agent_bridle_ceremony::authority::Assurance}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:9-27:14 -/
@[reducible]
def authority.Assurance.Insts.CoreCloneClone : core.clone.Clone
  authority.Assurance := {
  clone := authority.Assurance.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::marker::Copy for agent_bridle_ceremony::authority::Assurance}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:16-27:20 -/
@[reducible]
def authority.Assurance.Insts.CoreMarkerCopy : core.marker.Copy
  authority.Assurance := {
  cloneInst := authority.Assurance.Insts.CoreCloneClone
}

/-- [agent_bridle_ceremony::authority::{impl core::fmt::Debug for agent_bridle_ceremony::authority::Assurance}::fmt]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:22-27:27
    Visibility: public -/
def authority.Assurance.Insts.CoreFmtDebug.fmt
  (self : authority.Assurance) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | authority.Assurance.None => core.fmt.Formatter.write_str f (toStr "None")
  | authority.Assurance.Presence =>
    core.fmt.Formatter.write_str f (toStr "Presence")
  | authority.Assurance.Hardware =>
    core.fmt.Formatter.write_str f (toStr "Hardware")

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::fmt::Debug for agent_bridle_ceremony::authority::Assurance}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:22-27:27 -/
@[reducible]
def authority.Assurance.Insts.CoreFmtDebug : core.fmt.Debug authority.Assurance
  := {
  fmt := authority.Assurance.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::marker::StructuralPartialEq for agent_bridle_ceremony::authority::Assurance}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:29-27:38 -/
@[reducible]
def authority.Assurance.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq authority.Assurance := {
}

/-- [agent_bridle_ceremony::authority::{impl core::cmp::PartialEq<agent_bridle_ceremony::authority::Assurance> for agent_bridle_ceremony::authority::Assurance}::eq]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:29-27:38
    Visibility: public -/
def authority.Assurance.Insts.CoreCmpPartialEqAssurance.eq
  (self : authority.Assurance) (other : authority.Assurance) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::cmp::PartialEq<agent_bridle_ceremony::authority::Assurance> for agent_bridle_ceremony::authority::Assurance}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:29-27:38 -/
@[reducible]
def authority.Assurance.Insts.CoreCmpPartialEqAssurance : core.cmp.PartialEq
  authority.Assurance authority.Assurance := {
  eq := authority.Assurance.Insts.CoreCmpPartialEqAssurance.eq
}

/-- [agent_bridle_ceremony::authority::{impl core::cmp::Eq for agent_bridle_ceremony::authority::Assurance}::assert_fields_are_eq]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:40-27:42
    Visibility: public -/
def authority.Assurance.Insts.CoreCmpEq.assert_fields_are_eq
  (self : authority.Assurance) : Result Unit := do
  ok ()

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::cmp::Eq for agent_bridle_ceremony::authority::Assurance}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:40-27:42 -/
@[reducible]
def authority.Assurance.Insts.CoreCmpEq : core.cmp.Eq authority.Assurance := {
  partialEqInst := authority.Assurance.Insts.CoreCmpPartialEqAssurance
  assert_fields_are_eq :=
    authority.Assurance.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [agent_bridle_ceremony::authority::{impl core::hash::Hash for agent_bridle_ceremony::authority::Assurance}::hash]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:44-27:48
    Visibility: public -/
def authority.Assurance.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : authority.Assurance) (state : __H) :
  Result __H
  := do
  let self1 := read_discriminant self
  Isize.Insts.CoreHashHash.hash corehashHasherInst self1 state

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::hash::Hash for agent_bridle_ceremony::authority::Assurance}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 27:44-27:48 -/
@[reducible]
def authority.Assurance.Insts.CoreHashHash : core.hash.Hash authority.Assurance
  := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    authority.Assurance.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [agent_bridle_ceremony::authority::{impl core::clone::Clone for agent_bridle_ceremony::authority::Scope}::clone]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:9-36:14
    Visibility: public -/
def authority.Scope.Insts.CoreCloneClone.clone
  (self : authority.Scope) : Result authority.Scope := do
  ok self

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::clone::Clone for agent_bridle_ceremony::authority::Scope}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:9-36:14 -/
@[reducible]
def authority.Scope.Insts.CoreCloneClone : core.clone.Clone authority.Scope
  := {
  clone := authority.Scope.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::marker::Copy for agent_bridle_ceremony::authority::Scope}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:16-36:20 -/
@[reducible]
def authority.Scope.Insts.CoreMarkerCopy : core.marker.Copy authority.Scope
  := {
  cloneInst := authority.Scope.Insts.CoreCloneClone
}

/-- [agent_bridle_ceremony::authority::{impl core::fmt::Debug for agent_bridle_ceremony::authority::Scope}::fmt]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:22-36:27
    Visibility: public -/
def authority.Scope.Insts.CoreFmtDebug.fmt
  (self : authority.Scope) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | authority.Scope.Once => core.fmt.Formatter.write_str f (toStr "Once")
  | authority.Scope.Session => core.fmt.Formatter.write_str f (toStr "Session")
  | authority.Scope.Durable => core.fmt.Formatter.write_str f (toStr "Durable")

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::fmt::Debug for agent_bridle_ceremony::authority::Scope}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:22-36:27 -/
@[reducible]
def authority.Scope.Insts.CoreFmtDebug : core.fmt.Debug authority.Scope := {
  fmt := authority.Scope.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::marker::StructuralPartialEq for agent_bridle_ceremony::authority::Scope}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:29-36:38 -/
@[reducible]
def authority.Scope.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq authority.Scope := {
}

/-- [agent_bridle_ceremony::authority::{impl core::cmp::PartialEq<agent_bridle_ceremony::authority::Scope> for agent_bridle_ceremony::authority::Scope}::eq]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:29-36:38
    Visibility: public -/
def authority.Scope.Insts.CoreCmpPartialEqScope.eq
  (self : authority.Scope) (other : authority.Scope) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::cmp::PartialEq<agent_bridle_ceremony::authority::Scope> for agent_bridle_ceremony::authority::Scope}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:29-36:38 -/
@[reducible]
def authority.Scope.Insts.CoreCmpPartialEqScope : core.cmp.PartialEq
  authority.Scope authority.Scope := {
  eq := authority.Scope.Insts.CoreCmpPartialEqScope.eq
}

/-- [agent_bridle_ceremony::authority::{impl core::cmp::Eq for agent_bridle_ceremony::authority::Scope}::assert_fields_are_eq]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:40-36:42
    Visibility: public -/
def authority.Scope.Insts.CoreCmpEq.assert_fields_are_eq
  (self : authority.Scope) : Result Unit := do
  ok ()

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::cmp::Eq for agent_bridle_ceremony::authority::Scope}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:40-36:42 -/
@[reducible]
def authority.Scope.Insts.CoreCmpEq : core.cmp.Eq authority.Scope := {
  partialEqInst := authority.Scope.Insts.CoreCmpPartialEqScope
  assert_fields_are_eq := authority.Scope.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [agent_bridle_ceremony::authority::{impl core::hash::Hash for agent_bridle_ceremony::authority::Scope}::hash]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:44-36:48
    Visibility: public -/
def authority.Scope.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : authority.Scope) (state : __H) :
  Result __H
  := do
  let self1 := read_discriminant self
  Isize.Insts.CoreHashHash.hash corehashHasherInst self1 state

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::hash::Hash for agent_bridle_ceremony::authority::Scope}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 36:44-36:48 -/
@[reducible]
def authority.Scope.Insts.CoreHashHash : core.hash.Hash authority.Scope := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    authority.Scope.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Effect}::rank]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 45:4-50:5
    Visibility: public -/
def authority.Effect.rank (self : authority.Effect) : Result Std.U8 := do
  match self with
  | authority.Effect.Deny => ok 0#u8
  | authority.Effect.Allow => ok 1#u8

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Effect}::meet]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 53:4-59:5
    Visibility: public -/
def authority.Effect.meet
  (self : authority.Effect) (other : authority.Effect) :
  Result authority.Effect
  := do
  let i ← authority.Effect.rank self
  let i1 ← authority.Effect.rank other
  if i <= i1
  then ok self
  else ok other

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Effect}::ALL]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 62:4-62:63
    Visibility: public -/
@[global_simps, irreducible]
def authority.Effect.ALL : Array authority.Effect 2#usize :=
  Array.make 2#usize [ authority.Effect.Deny, authority.Effect.Allow ]

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Assurance}::rank]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 66:4-72:5
    Visibility: public -/
def authority.Assurance.rank (self : authority.Assurance) : Result Std.U8 := do
  match self with
  | authority.Assurance.None => ok 0#u8
  | authority.Assurance.Presence => ok 1#u8
  | authority.Assurance.Hardware => ok 2#u8

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Assurance}::meet]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 74:4-80:5
    Visibility: public -/
def authority.Assurance.meet
  (self : authority.Assurance) (other : authority.Assurance) :
  Result authority.Assurance
  := do
  let i ← authority.Assurance.rank self
  let i1 ← authority.Assurance.rank other
  if i <= i1
  then ok self
  else ok other

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Assurance}::ALL]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 82:4-82:96
    Visibility: public -/
@[global_simps, irreducible]
def authority.Assurance.ALL : Array authority.Assurance 3#usize :=
  Array.make 3#usize [
    authority.Assurance.None, authority.Assurance.Presence,
    authority.Assurance.Hardware
    ]

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Scope}::rank]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 86:4-92:5
    Visibility: public -/
def authority.Scope.rank (self : authority.Scope) : Result Std.U8 := do
  match self with
  | authority.Scope.Once => ok 0#u8
  | authority.Scope.Session => ok 1#u8
  | authority.Scope.Durable => ok 2#u8

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Scope}::meet]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 94:4-100:5
    Visibility: public -/
def authority.Scope.meet
  (self : authority.Scope) (other : authority.Scope) :
  Result authority.Scope
  := do
  let i ← authority.Scope.rank self
  let i1 ← authority.Scope.rank other
  if i <= i1
  then ok self
  else ok other

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Scope}::ALL]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 102:4-102:78
    Visibility: public -/
@[global_simps, irreducible]
def authority.Scope.ALL : Array authority.Scope 3#usize :=
  Array.make 3#usize [
    authority.Scope.Once, authority.Scope.Session, authority.Scope.Durable
    ]

/-- [agent_bridle_ceremony::authority::{impl core::clone::Clone for agent_bridle_ceremony::authority::Authority}::clone]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:9-106:14
    Visibility: public -/
def authority.Authority.Insts.CoreCloneClone.clone
  (self : authority.Authority) : Result authority.Authority := do
  ok self

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::clone::Clone for agent_bridle_ceremony::authority::Authority}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:9-106:14 -/
@[reducible]
def authority.Authority.Insts.CoreCloneClone : core.clone.Clone
  authority.Authority := {
  clone := authority.Authority.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::marker::Copy for agent_bridle_ceremony::authority::Authority}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:16-106:20 -/
@[reducible]
def authority.Authority.Insts.CoreMarkerCopy : core.marker.Copy
  authority.Authority := {
  cloneInst := authority.Authority.Insts.CoreCloneClone
}

/-- [agent_bridle_ceremony::authority::{impl core::fmt::Debug for agent_bridle_ceremony::authority::Authority}::fmt]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:22-106:27
    Visibility: public -/
def authority.Authority.Insts.CoreFmtDebug.fmt
  (self : authority.Authority) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ authority.Effect.Insts.CoreFmtDebug self.effect
  let dyn1 := Dyn.mk _ authority.Assurance.Insts.CoreFmtDebug self.assurance
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared authority.Scope.Insts.CoreFmtDebug)
      self.scope
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Authority") (toStr
    "effect") dyn (toStr "assurance") dyn1 (toStr "scope") dyn2

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::fmt::Debug for agent_bridle_ceremony::authority::Authority}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:22-106:27 -/
@[reducible]
def authority.Authority.Insts.CoreFmtDebug : core.fmt.Debug authority.Authority
  := {
  fmt := authority.Authority.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::marker::StructuralPartialEq for agent_bridle_ceremony::authority::Authority}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:29-106:38 -/
@[reducible]
def authority.Authority.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq authority.Authority := {
}

/-- [agent_bridle_ceremony::authority::{impl core::cmp::PartialEq<agent_bridle_ceremony::authority::Authority> for agent_bridle_ceremony::authority::Authority}::eq]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:29-106:38
    Visibility: public -/
def authority.Authority.Insts.CoreCmpPartialEqAuthority.eq
  (self : authority.Authority) (other : authority.Authority) :
  Result Bool
  := do
  let b ←
    authority.Effect.Insts.CoreCmpPartialEqEffect.eq self.effect other.effect
  if b
  then
    let b1 ←
      authority.Assurance.Insts.CoreCmpPartialEqAssurance.eq self.assurance
        other.assurance
    if b1
    then authority.Scope.Insts.CoreCmpPartialEqScope.eq self.scope other.scope
    else ok false
  else ok false

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::cmp::PartialEq<agent_bridle_ceremony::authority::Authority> for agent_bridle_ceremony::authority::Authority}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:29-106:38 -/
@[reducible]
def authority.Authority.Insts.CoreCmpPartialEqAuthority : core.cmp.PartialEq
  authority.Authority authority.Authority := {
  eq := authority.Authority.Insts.CoreCmpPartialEqAuthority.eq
}

/-- [agent_bridle_ceremony::authority::{impl core::cmp::Eq for agent_bridle_ceremony::authority::Authority}::assert_fields_are_eq]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:40-106:42
    Visibility: public -/
def authority.Authority.Insts.CoreCmpEq.assert_fields_are_eq
  (self : authority.Authority) : Result Unit := do
  ok ()

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::cmp::Eq for agent_bridle_ceremony::authority::Authority}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:40-106:42 -/
@[reducible]
def authority.Authority.Insts.CoreCmpEq : core.cmp.Eq authority.Authority := {
  partialEqInst := authority.Authority.Insts.CoreCmpPartialEqAuthority
  assert_fields_are_eq :=
    authority.Authority.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [agent_bridle_ceremony::authority::{impl core::hash::Hash for agent_bridle_ceremony::authority::Authority}::hash]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:44-106:48
    Visibility: public -/
def authority.Authority.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : authority.Authority) (state : __H) :
  Result __H
  := do
  let state1 ←
    authority.Effect.Insts.CoreHashHash.hash corehashHasherInst self.effect
      state
  let state2 ←
    authority.Assurance.Insts.CoreHashHash.hash corehashHasherInst
      self.assurance state1
  authority.Scope.Insts.CoreHashHash.hash corehashHasherInst self.scope state2

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::hash::Hash for agent_bridle_ceremony::authority::Authority}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 106:44-106:48 -/
@[reducible]
def authority.Authority.Insts.CoreHashHash : core.hash.Hash authority.Authority
  := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    authority.Authority.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Authority}::new]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 114:4-120:5
    Visibility: public -/
def authority.Authority.new
  (effect : authority.Effect) (assurance : authority.Assurance)
  (scope : authority.Scope) :
  Result authority.Authority
  := do
  ok { effect, assurance, scope }

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Authority}::BOTTOM]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 124:4-124:93
    Visibility: public -/
@[global_simps, irreducible]
def authority.Authority.BOTTOM : Result authority.Authority :=
  authority.Authority.new authority.Effect.Deny authority.Assurance.None
    authority.Scope.Once

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Authority}::TOP]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 129:4-129:98
    Visibility: public -/
@[global_simps, irreducible]
def authority.Authority.TOP : Result authority.Authority :=
  authority.Authority.new authority.Effect.Allow authority.Assurance.Hardware
    authority.Scope.Durable

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Authority}::meet]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 132:4-138:5
    Visibility: public -/
def authority.Authority.meet
  (self : authority.Authority) (other : authority.Authority) :
  Result authority.Authority
  := do
  let e ← authority.Effect.meet self.effect other.effect
  let a ← authority.Assurance.meet self.assurance other.assurance
  let s ← authority.Scope.meet self.scope other.scope
  authority.Authority.new e a s

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Authority}::le]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 141:4-143:5
    Visibility: public -/
def authority.Authority.le
  (self : authority.Authority) (other : authority.Authority) :
  Result Bool
  := do
  let a ← authority.Authority.meet self other
  authority.Authority.Insts.CoreCmpPartialEqAuthority.eq a self

/-- [agent_bridle_ceremony::authority::{agent_bridle_ceremony::authority::Authority}::attenuate]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 147:4-149:5
    Visibility: public -/
def authority.Authority.attenuate
  (self : authority.Authority) (ceiling : authority.Authority) :
  Result authority.Authority
  := do
  authority.Authority.meet self ceiling

/-- [agent_bridle_ceremony::authority::{impl core::clone::Clone for agent_bridle_ceremony::authority::Resolution}::clone]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:9-157:14
    Visibility: public -/
def authority.Resolution.Insts.CoreCloneClone.clone
  (self : authority.Resolution) : Result authority.Resolution := do
  ok self

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::clone::Clone for agent_bridle_ceremony::authority::Resolution}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:9-157:14 -/
@[reducible]
def authority.Resolution.Insts.CoreCloneClone : core.clone.Clone
  authority.Resolution := {
  clone := authority.Resolution.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::marker::Copy for agent_bridle_ceremony::authority::Resolution}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:16-157:20 -/
@[reducible]
def authority.Resolution.Insts.CoreMarkerCopy : core.marker.Copy
  authority.Resolution := {
  cloneInst := authority.Resolution.Insts.CoreCloneClone
}

/-- [agent_bridle_ceremony::authority::{impl core::fmt::Debug for agent_bridle_ceremony::authority::Resolution}::fmt]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:22-157:27
    Visibility: public -/
def authority.Resolution.Insts.CoreFmtDebug.fmt
  (self : authority.Resolution) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | authority.Resolution.NeedsDecision =>
    core.fmt.Formatter.write_str f (toStr "NeedsDecision")
  | authority.Resolution.Decided __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared authority.Authority.Insts.CoreFmtDebug)
        __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Decided") __self_01

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::fmt::Debug for agent_bridle_ceremony::authority::Resolution}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:22-157:27 -/
@[reducible]
def authority.Resolution.Insts.CoreFmtDebug : core.fmt.Debug
  authority.Resolution := {
  fmt := authority.Resolution.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::marker::StructuralPartialEq for agent_bridle_ceremony::authority::Resolution}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:29-157:38 -/
@[reducible]
def authority.Resolution.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq authority.Resolution := {
}

/-- [agent_bridle_ceremony::authority::{impl core::cmp::PartialEq<agent_bridle_ceremony::authority::Resolution> for agent_bridle_ceremony::authority::Resolution}::eq]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:29-157:38
    Visibility: public -/
def authority.Resolution.Insts.CoreCmpPartialEqResolution.eq
  (self : authority.Resolution) (other : authority.Resolution) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | authority.Resolution.NeedsDecision => ok true
    | authority.Resolution.Decided __self_0 =>
      match other with
      | authority.Resolution.NeedsDecision => ok true
      | authority.Resolution.Decided __arg1_0 =>
        authority.Authority.Insts.CoreCmpPartialEqAuthority.eq __self_0
          __arg1_0
  else ok false

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::cmp::PartialEq<agent_bridle_ceremony::authority::Resolution> for agent_bridle_ceremony::authority::Resolution}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:29-157:38 -/
@[reducible]
def authority.Resolution.Insts.CoreCmpPartialEqResolution : core.cmp.PartialEq
  authority.Resolution authority.Resolution := {
  eq := authority.Resolution.Insts.CoreCmpPartialEqResolution.eq
}

/-- [agent_bridle_ceremony::authority::{impl core::cmp::Eq for agent_bridle_ceremony::authority::Resolution}::assert_fields_are_eq]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:40-157:42
    Visibility: public -/
def authority.Resolution.Insts.CoreCmpEq.assert_fields_are_eq
  (self : authority.Resolution) : Result Unit := do
  ok ()

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::cmp::Eq for agent_bridle_ceremony::authority::Resolution}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:40-157:42 -/
@[reducible]
def authority.Resolution.Insts.CoreCmpEq : core.cmp.Eq authority.Resolution
  := {
  partialEqInst := authority.Resolution.Insts.CoreCmpPartialEqResolution
  assert_fields_are_eq :=
    authority.Resolution.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [agent_bridle_ceremony::authority::{impl core::hash::Hash for agent_bridle_ceremony::authority::Resolution}::hash]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:44-157:48
    Visibility: public -/
def authority.Resolution.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : authority.Resolution) (state : __H) :
  Result __H
  := do
  let self1 := read_discriminant self
  let state1 ← Isize.Insts.CoreHashHash.hash corehashHasherInst self1 state
  match self with
  | authority.Resolution.NeedsDecision => ok state1
  | authority.Resolution.Decided __self_0 =>
    authority.Authority.Insts.CoreHashHash.hash corehashHasherInst __self_0
      state1

/-- Trait implementation: [agent_bridle_ceremony::authority::{impl core::hash::Hash for agent_bridle_ceremony::authority::Resolution}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 157:44-157:48 -/
@[reducible]
def authority.Resolution.Insts.CoreHashHash : core.hash.Hash
  authority.Resolution := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    authority.Resolution.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [agent_bridle_ceremony::authority::resolve::{impl core::ops::function::FnMut<(agent_bridle_ceremony::authority::Authority, &'_ agent_bridle_ceremony::authority::Authority), agent_bridle_ceremony::authority::Authority> for agent_bridle_ceremony::authority::resolve::closure}::call_mut]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 171:76-171:97 -/
def
  authority.resolve.closure.Insts.CoreOpsFunctionFnMutPairAuthoritySharedAuthorityAuthority.call_mut
  (c : authority.resolve.closure)
  (tupled_args : (authority.Authority × authority.Authority)) :
  Result (authority.Authority × authority.resolve.closure)
  := do
  let (acc, a) := tupled_args
  let a1 ← authority.Authority.meet acc a
  ok (a1, c)

/-- [agent_bridle_ceremony::authority::resolve::{impl core::ops::function::FnOnce<(agent_bridle_ceremony::authority::Authority, &'_ agent_bridle_ceremony::authority::Authority), agent_bridle_ceremony::authority::Authority> for agent_bridle_ceremony::authority::resolve::closure}::call_once]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 171:76-171:97 -/
def
  authority.resolve.closure.Insts.CoreOpsFunctionFnOncePairAuthoritySharedAuthorityAuthority.call_once
  (c : authority.resolve.closure)
  (p : (authority.Authority × authority.Authority)) :
  Result authority.Authority
  := do
  let (a, _) ←
    authority.resolve.closure.Insts.CoreOpsFunctionFnMutPairAuthoritySharedAuthorityAuthority.call_mut
      c p
  ok a

/-- Trait implementation: [agent_bridle_ceremony::authority::resolve::{impl core::ops::function::FnOnce<(agent_bridle_ceremony::authority::Authority, &'_ agent_bridle_ceremony::authority::Authority), agent_bridle_ceremony::authority::Authority> for agent_bridle_ceremony::authority::resolve::closure}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 171:76-171:97 -/
@[reducible]
def
  authority.resolve.closure.Insts.CoreOpsFunctionFnOncePairAuthoritySharedAuthorityAuthority
  : core.ops.function.FnOnce authority.resolve.closure (authority.Authority ×
  authority.Authority) authority.Authority := {
  call_once :=
    authority.resolve.closure.Insts.CoreOpsFunctionFnOncePairAuthoritySharedAuthorityAuthority.call_once
}

/-- Trait implementation: [agent_bridle_ceremony::authority::resolve::{impl core::ops::function::FnMut<(agent_bridle_ceremony::authority::Authority, &'_ agent_bridle_ceremony::authority::Authority), agent_bridle_ceremony::authority::Authority> for agent_bridle_ceremony::authority::resolve::closure}]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 171:76-171:97 -/
@[reducible]
def
  authority.resolve.closure.Insts.CoreOpsFunctionFnMutPairAuthoritySharedAuthorityAuthority
  : core.ops.function.FnMut authority.resolve.closure (authority.Authority ×
  authority.Authority) authority.Authority := {
  FnOnceInst :=
    authority.resolve.closure.Insts.CoreOpsFunctionFnOncePairAuthoritySharedAuthorityAuthority
  call_mut :=
    authority.resolve.closure.Insts.CoreOpsFunctionFnMutPairAuthoritySharedAuthorityAuthority.call_mut
}

/-- [agent_bridle_ceremony::authority::resolve]:
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 168:0-173:1
    Visibility: public -/
def authority.resolve
  (candidates : Slice authority.Authority) : Result authority.Resolution := do
  let o ← core.slice.Slice.split_first candidates
  match o with
  | none => ok authority.Resolution.NeedsDecision
  | some p =>
    let (first, rest) := p
    let i ← core.slice.Slice.iter rest
    let a ←
      core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.fold
        authority.resolve.closure.Insts.CoreOpsFunctionFnMutPairAuthoritySharedAuthorityAuthority
        i first ()
    ok (authority.Resolution.Decided a)

/-- [agent_bridle_ceremony::boundary::{impl core::clone::Clone for agent_bridle_ceremony::boundary::Fence}::clone]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:9-25:14
    Visibility: public -/
def boundary.Fence.Insts.CoreCloneClone.clone
  (self : boundary.Fence) : Result boundary.Fence := do
  ok self

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::clone::Clone for agent_bridle_ceremony::boundary::Fence}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:9-25:14 -/
@[reducible]
def boundary.Fence.Insts.CoreCloneClone : core.clone.Clone boundary.Fence := {
  clone := boundary.Fence.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::marker::Copy for agent_bridle_ceremony::boundary::Fence}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:16-25:20 -/
@[reducible]
def boundary.Fence.Insts.CoreMarkerCopy : core.marker.Copy boundary.Fence := {
  cloneInst := boundary.Fence.Insts.CoreCloneClone
}

/-- [agent_bridle_ceremony::boundary::{impl core::fmt::Debug for agent_bridle_ceremony::boundary::Fence}::fmt]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:22-25:27
    Visibility: public -/
def boundary.Fence.Insts.CoreFmtDebug.fmt
  (self : boundary.Fence) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | boundary.Fence.Advisory =>
    core.fmt.Formatter.write_str f (toStr "Advisory")
  | boundary.Fence.Kernel => core.fmt.Formatter.write_str f (toStr "Kernel")

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::fmt::Debug for agent_bridle_ceremony::boundary::Fence}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:22-25:27 -/
@[reducible]
def boundary.Fence.Insts.CoreFmtDebug : core.fmt.Debug boundary.Fence := {
  fmt := boundary.Fence.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::marker::StructuralPartialEq for agent_bridle_ceremony::boundary::Fence}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:29-25:38 -/
@[reducible]
def boundary.Fence.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq boundary.Fence := {
}

/-- [agent_bridle_ceremony::boundary::{impl core::cmp::PartialEq<agent_bridle_ceremony::boundary::Fence> for agent_bridle_ceremony::boundary::Fence}::eq]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:29-25:38
    Visibility: public -/
def boundary.Fence.Insts.CoreCmpPartialEqFence.eq
  (self : boundary.Fence) (other : boundary.Fence) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::cmp::PartialEq<agent_bridle_ceremony::boundary::Fence> for agent_bridle_ceremony::boundary::Fence}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:29-25:38 -/
@[reducible]
def boundary.Fence.Insts.CoreCmpPartialEqFence : core.cmp.PartialEq
  boundary.Fence boundary.Fence := {
  eq := boundary.Fence.Insts.CoreCmpPartialEqFence.eq
}

/-- [agent_bridle_ceremony::boundary::{impl core::cmp::Eq for agent_bridle_ceremony::boundary::Fence}::assert_fields_are_eq]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:40-25:42
    Visibility: public -/
def boundary.Fence.Insts.CoreCmpEq.assert_fields_are_eq
  (self : boundary.Fence) : Result Unit := do
  ok ()

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::cmp::Eq for agent_bridle_ceremony::boundary::Fence}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:40-25:42 -/
@[reducible]
def boundary.Fence.Insts.CoreCmpEq : core.cmp.Eq boundary.Fence := {
  partialEqInst := boundary.Fence.Insts.CoreCmpPartialEqFence
  assert_fields_are_eq := boundary.Fence.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [agent_bridle_ceremony::boundary::{impl core::hash::Hash for agent_bridle_ceremony::boundary::Fence}::hash]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:44-25:48
    Visibility: public -/
def boundary.Fence.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : boundary.Fence) (state : __H) :
  Result __H
  := do
  let self1 := read_discriminant self
  Isize.Insts.CoreHashHash.hash corehashHasherInst self1 state

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::hash::Hash for agent_bridle_ceremony::boundary::Fence}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 25:44-25:48 -/
@[reducible]
def boundary.Fence.Insts.CoreHashHash : core.hash.Hash boundary.Fence := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    boundary.Fence.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [agent_bridle_ceremony::boundary::{agent_bridle_ceremony::boundary::Fence}::ALL]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 32:4-32:65
    Visibility: public -/
@[global_simps, irreducible]
def boundary.Fence.ALL : Array boundary.Fence 2#usize :=
  Array.make 2#usize [ boundary.Fence.Advisory, boundary.Fence.Kernel ]

/-- [agent_bridle_ceremony::boundary::{impl core::clone::Clone for agent_bridle_ceremony::boundary::Request}::clone]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:9-38:14
    Visibility: public -/
def boundary.Request.Insts.CoreCloneClone.clone
  (self : boundary.Request) : Result boundary.Request := do
  ok self

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::clone::Clone for agent_bridle_ceremony::boundary::Request}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:9-38:14 -/
@[reducible]
def boundary.Request.Insts.CoreCloneClone : core.clone.Clone boundary.Request
  := {
  clone := boundary.Request.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::marker::Copy for agent_bridle_ceremony::boundary::Request}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:16-38:20 -/
@[reducible]
def boundary.Request.Insts.CoreMarkerCopy : core.marker.Copy boundary.Request
  := {
  cloneInst := boundary.Request.Insts.CoreCloneClone
}

/-- [agent_bridle_ceremony::boundary::{impl core::fmt::Debug for agent_bridle_ceremony::boundary::Request}::fmt]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:22-38:27
    Visibility: public -/
def boundary.Request.Insts.CoreFmtDebug.fmt
  (self : boundary.Request) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool) self.dynamic
  core.fmt.Formatter.debug_struct_field1_finish f (toStr "Request") (toStr
    "dynamic") dyn

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::fmt::Debug for agent_bridle_ceremony::boundary::Request}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:22-38:27 -/
@[reducible]
def boundary.Request.Insts.CoreFmtDebug : core.fmt.Debug boundary.Request := {
  fmt := boundary.Request.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::marker::StructuralPartialEq for agent_bridle_ceremony::boundary::Request}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:29-38:38 -/
@[reducible]
def boundary.Request.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq boundary.Request := {
}

/-- [agent_bridle_ceremony::boundary::{impl core::cmp::PartialEq<agent_bridle_ceremony::boundary::Request> for agent_bridle_ceremony::boundary::Request}::eq]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:29-38:38
    Visibility: public -/
def boundary.Request.Insts.CoreCmpPartialEqRequest.eq
  (self : boundary.Request) (other : boundary.Request) : Result Bool := do
  ok (self.dynamic = other.dynamic)

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::cmp::PartialEq<agent_bridle_ceremony::boundary::Request> for agent_bridle_ceremony::boundary::Request}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:29-38:38 -/
@[reducible]
def boundary.Request.Insts.CoreCmpPartialEqRequest : core.cmp.PartialEq
  boundary.Request boundary.Request := {
  eq := boundary.Request.Insts.CoreCmpPartialEqRequest.eq
}

/-- [agent_bridle_ceremony::boundary::{impl core::cmp::Eq for agent_bridle_ceremony::boundary::Request}::assert_fields_are_eq]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:40-38:42
    Visibility: public -/
def boundary.Request.Insts.CoreCmpEq.assert_fields_are_eq
  (self : boundary.Request) : Result Unit := do
  ok ()

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::cmp::Eq for agent_bridle_ceremony::boundary::Request}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:40-38:42 -/
@[reducible]
def boundary.Request.Insts.CoreCmpEq : core.cmp.Eq boundary.Request := {
  partialEqInst := boundary.Request.Insts.CoreCmpPartialEqRequest
  assert_fields_are_eq := boundary.Request.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [agent_bridle_ceremony::boundary::{impl core::hash::Hash for agent_bridle_ceremony::boundary::Request}::hash]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:44-38:48
    Visibility: public -/
def boundary.Request.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : boundary.Request) (state : __H) :
  Result __H
  := do
  Bool.Insts.CoreHashHash.hash corehashHasherInst self.dynamic state

/-- Trait implementation: [agent_bridle_ceremony::boundary::{impl core::hash::Hash for agent_bridle_ceremony::boundary::Request}]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 38:44-38:48 -/
@[reducible]
def boundary.Request.Insts.CoreHashHash : core.hash.Hash boundary.Request := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    boundary.Request.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [agent_bridle_ceremony::boundary::{agent_bridle_ceremony::boundary::Request}::new]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 44:4-46:5
    Visibility: public -/
def boundary.Request.new (dynamic : Bool) : Result boundary.Request := do
  ok { dynamic }

/-- [agent_bridle_ceremony::boundary::{agent_bridle_ceremony::boundary::Request}::ALL]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 48:4-48:76
    Visibility: public -/
@[global_simps, irreducible]
def boundary.Request.ALL : Result (Array boundary.Request 2#usize) := do
  let r ← boundary.Request.new false
  let r1 ← boundary.Request.new true
  ok (Array.make 2#usize [ r, r1 ])

/-- [agent_bridle_ceremony::boundary::safe_subset]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 53:0-59:1
    Visibility: public -/
def boundary.safe_subset (q : boundary.Request) : Result authority.Effect := do
  if q.dynamic
  then ok authority.Effect.Deny
  else ok authority.Effect.Allow

/-- [agent_bridle_ceremony::boundary::brush_honest]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 66:0-72:1
    Visibility: public -/
def boundary.brush_honest
  (f : boundary.Fence) (q : boundary.Request) : Result authority.Effect := do
  match f with
  | boundary.Fence.Advisory =>
    if q.dynamic
    then ok authority.Effect.Deny
    else ok authority.Effect.Allow
  | boundary.Fence.Kernel => ok authority.Effect.Allow

/-- [agent_bridle_ceremony::boundary::boundary_verdict]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 76:0-81:1
    Visibility: public -/
def boundary.boundary_verdict
  (f : boundary.Fence) (q : boundary.Request) : Result authority.Effect := do
  match f with
  | boundary.Fence.Advisory => boundary.safe_subset q
  | boundary.Fence.Kernel => boundary.brush_honest boundary.Fence.Kernel q

/-- [agent_bridle_ceremony::boundary::enforceable_ceiling]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 84:0-86:1
    Visibility: public -/
def boundary.enforceable_ceiling
  (f : boundary.Fence) (q : boundary.Request) : Result authority.Effect := do
  boundary.boundary_verdict f q

/-- [agent_bridle_ceremony::boundary::boundary_ceiling]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 90:0-92:1
    Visibility: public -/
def boundary.boundary_ceiling
  (f : boundary.Fence) (q : boundary.Request) :
  Result authority.Authority
  := do
  let e ← boundary.boundary_verdict f q
  authority.Authority.new e authority.Assurance.Hardware
    authority.Scope.Durable

/-- [agent_bridle_ceremony::boundary::minted_grant]:
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 96:0-98:1
    Visibility: public -/
def boundary.minted_grant
  (req : authority.Authority) (f : boundary.Fence) (q : boundary.Request) :
  Result authority.Authority
  := do
  let a ← boundary.boundary_ceiling f q
  authority.Authority.attenuate req a

end agent_bridle_ceremony
