-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [agent_bridle_ceremony]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import AgentBridleCeremony.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open agent_bridle_ceremony

/-- [core::hash::impls::{impl core::hash::Hash for isize}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<isize>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<isize>}::hash"]
axiom Isize.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.Isize → H → Result H

/-- [core::hash::impls::{impl core::hash::Hash for bool}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 848:8-848:48
    Name pattern: [core::hash::impls::{core::hash::Hash<bool>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<bool>}::hash"]
axiom Bool.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Bool → H → Result H

