-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [agent_bridle_ceremony]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace agent_bridle_ceremony

/-- [agent_bridle_ceremony::authority::Effect]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 19:0-22:1
    Visibility: public -/
@[discriminant isize]
inductive authority.Effect where
| Deny : authority.Effect
| Allow : authority.Effect

/-- [agent_bridle_ceremony::authority::Assurance]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 28:0-32:1
    Visibility: public -/
@[discriminant isize]
inductive authority.Assurance where
| None : authority.Assurance
| Presence : authority.Assurance
| Hardware : authority.Assurance

/-- [agent_bridle_ceremony::authority::Scope]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 37:0-41:1
    Visibility: public -/
@[discriminant isize]
inductive authority.Scope where
| Once : authority.Scope
| Session : authority.Scope
| Durable : authority.Scope

/-- [agent_bridle_ceremony::authority::Authority]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 107:0-111:1
    Visibility: public -/
structure authority.Authority where
  effect : authority.Effect
  assurance : authority.Assurance
  scope : authority.Scope

/-- [agent_bridle_ceremony::authority::Resolution]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 158:0-161:1
    Visibility: public -/
@[discriminant isize]
inductive authority.Resolution where
| NeedsDecision : authority.Resolution
| Decided : authority.Authority → authority.Resolution

/-- [agent_bridle_ceremony::boundary::Fence]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 26:0-29:1
    Visibility: public -/
@[discriminant isize]
inductive boundary.Fence where
| Advisory : boundary.Fence
| Kernel : boundary.Fence

/-- [agent_bridle_ceremony::boundary::Request]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 39:0-41:1
    Visibility: public -/
structure boundary.Request where
  dynamic : Bool

end agent_bridle_ceremony
