-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [agent_bridle_ceremony]: type definitions
import Aeneas
import AgentBridleCeremony.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace agent_bridle_ceremony

/-- [agent_bridle_ceremony::authority::Effect]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 19:0-22:1
    Visibility: public -/
@[discriminant isize]
inductive authority.Effect where
| Deny : authority.Effect
| Allow : authority.Effect

/-- [agent_bridle_ceremony::authority::Assurance]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 28:0-32:1
    Visibility: public -/
@[discriminant isize]
inductive authority.Assurance where
| None : authority.Assurance
| Presence : authority.Assurance
| Hardware : authority.Assurance

/-- [agent_bridle_ceremony::authority::Scope]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 37:0-41:1
    Visibility: public -/
@[discriminant isize]
inductive authority.Scope where
| Once : authority.Scope
| Session : authority.Scope
| Durable : authority.Scope

/-- [agent_bridle_ceremony::authority::Authority]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 107:0-111:1
    Visibility: public -/
structure authority.Authority where
  effect : authority.Effect
  assurance : authority.Assurance
  scope : authority.Scope

/-- [agent_bridle_ceremony::authority::Resolution]
    Source: 'agent-bridle-ceremony/src/authority.rs', lines 158:0-161:1
    Visibility: public -/
@[discriminant isize]
inductive authority.Resolution where
| NeedsDecision : authority.Resolution
| Decided : authority.Authority → authority.Resolution

/-- [agent_bridle_ceremony::boundary::Fence]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 26:0-29:1
    Visibility: public -/
@[discriminant isize]
inductive boundary.Fence where
| Advisory : boundary.Fence
| Kernel : boundary.Fence

/-- [agent_bridle_ceremony::boundary::Request]
    Source: 'agent-bridle-ceremony/src/boundary.rs', lines 39:0-41:1
    Visibility: public -/
structure boundary.Request where
  dynamic : Bool

/-- [agent_bridle_ceremony::chain_store::StoreId]
    Source: 'agent-bridle-ceremony/src/chain_store.rs', lines 67:0-67:24
    Visibility: public -/
@[reducible]
def chain_store.StoreId := Std.U64

/-- [agent_bridle_ceremony::chain_store::ThreadId]
    Source: 'agent-bridle-ceremony/src/chain_store.rs', lines 72:0-72:25
    Visibility: public -/
@[reducible]
def chain_store.ThreadId := Std.U64

/-- [agent_bridle_ceremony::chain_store::LineCid]
    Source: 'agent-bridle-ceremony/src/chain_store.rs', lines 81:0-81:24
    Visibility: public -/
@[reducible]
def chain_store.LineCid := Std.U64

/-- [agent_bridle_ceremony::chain_store::AuthorityCheckpoint]
    Source: 'agent-bridle-ceremony/src/chain_store.rs', lines 113:0-122:1
    Visibility: public -/
structure chain_store.AuthorityCheckpoint where
  store_id : chain_store.StoreId
  thread_id : chain_store.ThreadId
  sequence : Std.U64
  head : chain_store.LineCid

/-- [agent_bridle_ceremony::chain_store::AppendOutcome]
    Source: 'agent-bridle-ceremony/src/chain_store.rs', lines 127:0-143:1
    Visibility: public -/
@[discriminant isize]
inductive chain_store.AppendOutcome where
| Committed : Std.U64 → chain_store.LineCid → chain_store.AppendOutcome
| CasLost : Option chain_store.LineCid → chain_store.AppendOutcome
| Rejected : Option chain_store.LineCid → chain_store.AppendOutcome

/-- [agent_bridle_ceremony::chain_store::Rejection]
    Source: 'agent-bridle-ceremony/src/chain_store.rs', lines 158:0-174:1
    Visibility: public -/
@[discriminant isize]
inductive chain_store.Rejection where
| DifferentStore : chain_store.Rejection
| DifferentThread : chain_store.Rejection
| NotForward : chain_store.Rejection
| Sibling : chain_store.Rejection
| BeyondSpine : chain_store.Rejection

/-- [agent_bridle_ceremony::chain_store::AcceptOutcome]
    Source: 'agent-bridle-ceremony/src/chain_store.rs', lines 147:0-153:1
    Visibility: public -/
@[discriminant isize]
inductive chain_store.AcceptOutcome where
| Accepted : Std.U64 → chain_store.AcceptOutcome
| Rejected : chain_store.Rejection → chain_store.AcceptOutcome

/-- [agent_bridle_ceremony::chain_store::ChainStore]
    Source: 'agent-bridle-ceremony/src/chain_store.rs', lines 182:0-191:1
    Visibility: public -/
structure chain_store.ChainStore where
  store_id : chain_store.StoreId
  thread_id : chain_store.ThreadId
  spine : alloc.vec.Vec chain_store.LineCid
  checkpoint : Std.U64

/-- [agent_bridle_ceremony::signed_object::HashAlgorithm]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 65:0-73:1
    Visibility: public -/
@[discriminant isize]
inductive signed_object.HashAlgorithm where
| Blake3_256 : signed_object.HashAlgorithm
| Sha1 : signed_object.HashAlgorithm

/-- [agent_bridle_ceremony::signed_object::SignatureAlgorithm]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 82:0-90:1
    Visibility: public -/
@[discriminant isize]
inductive signed_object.SignatureAlgorithm where
| Ed25519 : signed_object.SignatureAlgorithm
| Ecdsa : signed_object.SignatureAlgorithm

/-- [agent_bridle_ceremony::signed_object::Codec]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 109:0-116:1
    Visibility: public -/
@[discriminant isize]
inductive signed_object.Codec where
| DagCbor : signed_object.Codec
| Json : signed_object.Codec

/-- [agent_bridle_ceremony::signed_object::Profile]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 130:0-135:1
    Visibility: public -/
structure signed_object.Profile where
  version : Std.U64
  hashes : alloc.vec.Vec signed_object.HashAlgorithm
  signatures : alloc.vec.Vec signed_object.SignatureAlgorithm
  codecs : alloc.vec.Vec signed_object.Codec

/-- [agent_bridle_ceremony::signed_object::TrustedProfile]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 173:0-175:1
    Visibility: public -/
structure signed_object.TrustedProfile where
  profile : signed_object.Profile

/-- [agent_bridle_ceremony::signed_object::AllowedHash]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 215:0-217:1
    Visibility: public -/
structure signed_object.AllowedHash where
  algorithm : signed_object.HashAlgorithm

/-- [agent_bridle_ceremony::signed_object::AllowedSignature]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 236:0-238:1
    Visibility: public -/
structure signed_object.AllowedSignature where
  algorithm : signed_object.SignatureAlgorithm

/-- [agent_bridle_ceremony::signed_object::AllowedCodec]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 256:0-258:1
    Visibility: public -/
structure signed_object.AllowedCodec where
  codec : signed_object.Codec

/-- [agent_bridle_ceremony::signed_object::SignatureDomain]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 310:0-314:1
    Visibility: public -/
structure signed_object.SignatureDomain where
  record_type : String
  store_id : alloc.vec.Vec Std.U8
  thread_or_principal : alloc.vec.Vec Std.U8

/-- [agent_bridle_ceremony::signed_object::DomainBinding]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 322:0-326:1
    Visibility: public -/
structure signed_object.DomainBinding where
  profile_version : Std.U64
  codec : signed_object.Codec
  signer : alloc.vec.Vec Std.U8

/-- [agent_bridle_ceremony::signed_object::SignaturePreimage]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 343:0-366:1
    Visibility: public -/
structure signed_object.SignaturePreimage where
  canonical_unsigned : alloc.vec.Vec Std.U8
  profile_version : Std.U64
  hash_algorithm : signed_object.HashAlgorithm
  signature_algorithm : signed_object.SignatureAlgorithm
  codec : signed_object.Codec
  domain : signed_object.SignatureDomain
  body : alloc.vec.Vec Std.U8
  claimed_cid : alloc.vec.Vec Std.U8
  signer : alloc.vec.Vec Std.U8
  unknown_critical : alloc.vec.Vec String

/-- Trait declaration: [agent_bridle_ceremony::signed_object::CanonicalEncoding]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 381:0-386:1
    Visibility: public -/
structure signed_object.CanonicalEncoding (Self : Type) (Self_Value : Type)
  where
  encode : Self → Self_Value → Result (alloc.vec.Vec Std.U8)

/-- Trait declaration: [agent_bridle_ceremony::signed_object::CanonicalPayloadDecoder]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 393:0-397:1
    Visibility: public -/
structure signed_object.CanonicalPayloadDecoder (Self : Type)
  (Self_Clause0_Value : Type) where
  CanonicalEncodingInst : signed_object.CanonicalEncoding Self
    Self_Clause0_Value
  parse : Self → Slice Std.U8 → Result (Option Self_Clause0_Value)

/-- Trait declaration: [agent_bridle_ceremony::signed_object::SignedEnvelopeCodec]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 410:0-475:1
    Visibility: public -/
structure signed_object.SignedEnvelopeCodec (Self : Type) (Self_Envelope :
  Type) (Self_Unsigned : Type) where
  decode : Self → Slice Std.U8 → Result (Option Self_Envelope)
  encode : Self → Self_Envelope → Result (alloc.vec.Vec Std.U8)
  unsigned : Self → Self_Envelope → Result Self_Unsigned
  encode_unsigned : Self → Self_Unsigned → Result (alloc.vec.Vec Std.U8)
  profile_version : Self → Self_Unsigned → Result Std.U64
  hash_algorithm : Self → Self_Unsigned → Result
    signed_object.HashAlgorithm
  signature_algorithm : Self → Self_Unsigned → Result
    signed_object.SignatureAlgorithm
  codec : Self → Self_Unsigned → Result signed_object.Codec
  domain : Self → Self_Unsigned → Result signed_object.SignatureDomain
  body : Self → Self_Unsigned → Result (alloc.vec.Vec Std.U8)
  claimed_cid : Self → Self_Unsigned → Result (alloc.vec.Vec Std.U8)
  signer : Self → Self_Unsigned → Result (alloc.vec.Vec Std.U8)
  unknown_critical : Self → Self_Unsigned → Result (alloc.vec.Vec String)
  body_binding : Self → Self_Unsigned → Result signed_object.DomainBinding
  signature_bytes : Self → Self_Envelope → Result (alloc.vec.Vec Std.U8)
  signature_preimage : Self → Self_Unsigned → Result
    signed_object.SignaturePreimage

/-- Trait declaration: [agent_bridle_ceremony::signed_object::CryptoBoundary]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 491:0-503:1
    Visibility: public -/
structure signed_object.CryptoBoundary (Self : Type) where
  digest : Self → signed_object.AllowedHash → Slice Std.U8 → Result
    (alloc.vec.Vec Std.U8)
  signature_matches : Self → signed_object.AllowedSignature →
    signed_object.SignaturePreimage → Slice Std.U8 → Result Bool

/-- [agent_bridle_ceremony::signed_object::VerifyRejection]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 515:0-545:1
    Visibility: public -/
@[discriminant isize]
inductive signed_object.VerifyRejection where
| Undecodable : signed_object.VerifyRejection
| VersionMismatch : signed_object.VerifyRejection
| HashNotAllowed : signed_object.VerifyRejection
| SignatureAlgNotAllowed : signed_object.VerifyRejection
| CodecNotAllowed : signed_object.VerifyRejection
| SignatureInvalid : signed_object.VerifyRejection
| CidMismatch : signed_object.VerifyRejection
| BodyDomainMismatch : signed_object.VerifyRejection
| UnknownCriticalField : signed_object.VerifyRejection
| NonCanonicalBody : signed_object.VerifyRejection
| NonCanonicalEnvelope : signed_object.VerifyRejection

/-- [agent_bridle_ceremony::signed_object::VerifiedEnvelope]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 552:0-561:1
    Visibility: public -/
structure signed_object.VerifiedEnvelope (E : Type) where
  envelope : E
  profile : signed_object.Profile
  allowed_hash : signed_object.AllowedHash
  allowed_signature : signed_object.AllowedSignature
  allowed_codec : signed_object.AllowedCodec
  preimage : signed_object.SignaturePreimage

/-- [agent_bridle_ceremony::signed_object::Sealed]
    Source: 'agent-bridle-ceremony/src/signed_object.rs', lines 614:0-617:1
    Visibility: public -/
structure signed_object.Sealed (V : Type) (E : Type) where
  verified : signed_object.VerifiedEnvelope E
  value : V

end agent_bridle_ceremony
